server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    #实例不注册到 Eureka Server 只是以供其他实例发现（只是作为注册中心）
    registerWithEureka: false
    #客户端不会从 Eureka Server 获取实例注册信息（不会拉取信息，只是存储信息）
    fetchRegistry: false
    #客户端需要注册的 Eureka Server 的地址
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
  server:
    #表示注册中心是否开启服务的自我保护能力（false 关闭自我保护，不管如何都要剔除心跳检测异常的服务）
    enableSelfPreservation: false